name: preojeto
description: "Projeto Restaurante."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  image_network: ^2.5.4+1
  get_it: ^8.0.0
  shared_preferences: ^2.0.13 
  logger: ^1.4.0 
  path_provider: ^2.1.4
  video_player: ^2.4.5
  audioplayers: ^6.0.1
  just_audio: ^0.9.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - lib/images/
    - lib/videos/
    - lib/audios/
